# Generated by Django 4.2.2 on 2023-06-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
